### ISSUE TITLE
Be able to highlight text in responses according to matching terms

### ISSUE THREAD

**Issue by acodeninja** [acodeninja/modern-tools-for-social-care#22]
### What does it do now?
Does not return the results with highlighting for the terms entered.

### What should it do?
Return results with highlighting for the terms.

**Comment by jhackett1** [comment]
example

https://github.com/LBHackney-IT/lbh-social-care-next-gen-search/blob/main/pages/api/search.ts#L66-L74


```
            highlight: {
              type: "fvh",
              pre_tags: "<strong>",
              post_tags: "</strong>",
              fields: {
                content: {},
                "content.exact": {},
              },
            },
```

we want to use the `fvh` highlighter and `<strong/>` tags to wrap the highlighted text
